# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ae3bf93e7b581f256af0eb34aaa7cd680273c3c51c4dbd9d0f54baa8c7e8eaf1cdf4a89a5937e81ae3737c5dd8b0fd38bf5c8ce47f4fac59cbe66a64ca020d9c

test:
  secret_key_base: ec43899381ff4d89f7e7c4088369940216cb460dbcb73bddc93ee31223283b6af3cc40908f73341b7e05257656c1d802061b921d0c8e30f1de809f1c3cf84f45

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
